#!/bin/bash

action="$1"

if [ "$action" = configure ]; then
    # add user "deepin_anything_server"
    #create user if not exists
    user=deepin_anything_server
    id $user >& /dev/null
    if [ $? = 0 ]
    then
        set -e
        usermod -s /usr/sbin/nologin $user
        exit 0
    fi

    set -e
    useradd -M -s /usr/sbin/nologin $user || (echo "Failed on add user deepin_anything_server" && false)
fi

#DEBHELPER#
